name: Release rollback

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag id to build and deploy in prod'
        required: true
        type: string
jobs:
  release_rollback_build:
    runs-on: ubuntu-latest
    if:  ${{ inputs.release_tag }} 
    steps:
      - name: Print the release tag to STDOUT
        run: echo  The release tag is ${{ inputs.release_tag }} 
      - name: Checkout Tag
        uses: actions/checkout@v2
        with:
          ref: tags/${{ inputs.release_tag }} 
          fetch-depth: '0'
 
