name: Fetch Second-to-Last Tag

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
jobs:
  fetch_second_last_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch Git Tags
        id: fetch_tags
        run: |
          git fetch --depth=1 --tags
          tags=$(git rev-list --tags --max-count=2)
          second_last_tag=$(echo "$tags" | sed -n '2p')
          echo "::set-output name=second_last_tag::$second_last_tag"
      
      - name: Echo Second-to-Last Tag
        run: echo "Second-to-last tag is ${{ steps.fetch_tags.outputs.second_last_tag }}"
      - name: Checkout Tag
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.fetch_tags.outputs.second_last_tag }}
