name: Fetch Second-to-Last Tag

on:
  workflow_dispatch:
  push:
    branches:
     - main
jobs:
  fetch_second_last_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Git Tags
        id: fetch_tags
        run: |
          git fetch --depth=1 --tags
          tags=$(git rev-list --tags --max-count=2)
          second_last_tag=$(echo "$tags" | sed -n '2p')
          echo "::set-output name=second_last_tag::$second_last_tag"
      
      - name: Echo Second-to-Last Tag
        run: echo "Second-to-last tag is ${{ steps.fetch_tags.outputs.second_last_tag }}"
