name: Test
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.base }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 100
    - name: Sets env vars for base image
      id: step1
      run: |
          set -x
          echo "base=$(cat deploy/Dockerfile | head -n 1 | awk -F" " '{print $2}')" >> $GITHUB_OUTPUT
    - name: Test
      run: echo $BASE_IMAGE_NAME
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
  test: 
    needs: build
    runs-on: ubuntu-latest
    #container: 
    #    image: ${{env.BASE_IMAGE_NAME}}
    steps:
      - run: echo ${{needs.build.outputs.output1}}
        

