name: Test
on:
  push:
    branches:
      - main
    paths:
    - 'deploy/test/upload/**'
    - 'docker/fastapi-auth/**'
    - docker/fastapi-celery
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.base }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/upload-artifact@v3
      with:
       name: my-artifact
       path: deploy/
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    - name: Print paths filter variable
      run: echo "${{ github.event.inputs.path }}"
    - name: Get path of changed files
      id: path
      run: |
        echo "path=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | cut -d'/' -f 1,2)"  >> $GITHUB_OUTPUT
        echo "base=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | cut -d'/' -f 2)"  >> $GITHUB_OUTPUT
    - name: Do something with the path
      run: |
       echo "Changed files path: ${{ steps.path.outputs.path }}"
       echo "imageRepository=catexpert-${{ steps.path.outputs.path }}" >> $GITHUB_ENV
    - name: Set environment variables based on path
      run: |
          if [ "${{ steps.path.outputs.path }}" = "docker/fastapi-auth" ]; then
            echo "Setting environment for fastapi-auth"
            #echo "imageRepository=catexpert-fastapi-auth" >> $GITHUB_ENV
          elif [ "${{ steps.path.outputs.path }}" = "docker/fastapi-celery" ]; then
            echo "Setting environment for fastapi-celery"
            #echo "imageRepository=catexpert-fastapi-celery" >> $GITHUB_ENV
          else
            echo "Setting environment variable FOO to 'not main'"
            echo "FOO=not main" >> $GITHUB_ENV
          fi
    - name: Print paths env variable
      run: echo "${{ env.imageRepository }}"
    - name: Sets env vars for base image
      id: step1
      run: |
          set -x
          echo "base=$(cat deploy/Dockerfile | head -n 1 | awk -F" " '{print $2}')" >> $GITHUB_OUTPUT
    - name: Test
      run: echo $BASE_IMAGE_NAME
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
  test: 
    needs: build
    runs-on: ubuntu-latest
    container: 
        image: ${{needs.build.outputs.output1}}
    steps:
      - run: echo ${{needs.build.outputs.output1}}
        

