name: Test
on:
  push:
    branches:
      - main
    paths:
    - 'deploy/test/upload/**'
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.base }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/upload-artifact@v3
      with:
       name: my-artifact
       path: deploy/
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    - name: Print paths filter variable
      run: echo "${{ github.event.inputs.path }}"
    - name: Get path of changed files
      id: path
      run: echo "::set-output name=path::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
    - name: Do something with the path
      run: |
       echo "Changed files path: ${{ steps.path.outputs.path }}"
    - name: Sets env vars for base image
      id: step1
      run: |
          set -x
          echo "base=$(cat deploy/Dockerfile | head -n 1 | awk -F" " '{print $2}')" >> $GITHUB_OUTPUT
    - name: Test
      run: echo $BASE_IMAGE_NAME
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
  test: 
    needs: build
    runs-on: ubuntu-latest
    container: 
        image: ${{needs.build.outputs.output1}}
    steps:
      - run: echo ${{needs.build.outputs.output1}}
        

